### ISSUE TITLE
Link To Slides

### ISSUE THREAD

**Issue by FlorianWendelborn** [tejasmanohar/koa-starter#1]
As far as I understand, this repo only exists because of [these slides](http://slides.com/tejasmanohar/koa-es6). I think you should set this as the GitHub repo link, so people seeing this repo can see what it's for.

**Comment by tejasmanohar** [comment]
PR :D

**Comment by FlorianWendelborn** [comment]
I can't pull request that link, since it's not managed by git. You have to set it up yourself or give me administrative permissions on this repo. I'm talking about the `No description or website provided.` headline of the Repo.

**Comment by tejasmanohar** [comment]
ohhhhh

**Comment by tejasmanohar** [comment]
done
